---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

paths:
  .github/workflows/github2gerrit.yaml:
    ignore:
      - 'property "job_workflow_(ref|sha)" is not defined in object type .+'
  .github/workflows/openssf-scorecard.yaml:
    ignore:
      # yamllint disable-line rule:line-length
      - 'reusable workflow call "lfit/releng-reusable-workflows/\.github/workflows/reuse-openssf-scorecard\.yaml@[0-9a-f]{40}" has no explicit cache access limit'
  .github/workflows/testing.yaml:
    ignore:
      - 'input "invalid_input" is not defined in action .+'
      - 'missing input "input" which is required by action .+'
      - 'specifying action "\$/" in invalid format because path is missing'
