---
# SPDX-FileCopyrightText: 2025 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0

name: 'Release Drafter'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: "rd-push-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  update_release_draft:
    name: 'Update Release Draft'
    permissions:
      # write permission is required to create releases
      contents: write
    runs-on: 'ubuntu-latest'
    timeout-minutes: 3
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: 'audit'

      - name: 'Show concurrency group'
        shell: bash
        run: |
          # Show concurrency group
          GROUP="rd-push-${{ github.ref }}"
          {
            echo '## Release Drafter'
            echo "Concurrency group: ${GROUP}"
          } >> "$GITHUB_STEP_SUMMARY"
          echo "Concurrency group: ${GROUP}"

      - name: 'Update draft release'
        # yamllint disable-line rule:line-length
        uses: release-drafter/release-drafter@44a942e465867c7465b76aa808ddca6e0acae5da # v7.1.0
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
